services:
  - type: web
    name: smart-skill-backend
    env: node
    plan: free

    buildCommand: npm install
    startCommand: npm run dev

    autoDeploy: true

    envVars:
      - key: NODE_ENV
        value: production

      - key: MONGO_URI
        sync: false   